# Generated by Django 5.0.7 on 2024-10-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='header_bot',
        ),
    ]
