# Generated by Django 5.0.7 on 2024-10-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_footer_header_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='header_bot',
            new_name='Footer',
        ),
    ]
